projet_dbt:
  target: dev
  outputs:
    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: Trino
      password:  # required if method is ldap or kerberos
      catalog: lakehouse
      host: localhost
      port: 8080
      schema: bronze  # a faire essayer d'envoyer vers silver
      # table : weatheronepoint 
      threads: 1
    gold:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: Trino
      password:  # required if method is ldap or kerberos
      catalog: clickhouse
      host: localhost
      port: 8080
      schema: gold  # a faire essayer d'envoyer vers silver





