apiVersion: v1
kind: Service
metadata:
  matchLabels:
      app: airbyte-webapp
spec:
  selector:
    app: myapp   # Remplacez ceci par le label de votre déploiement
  ports:
  - protocol: TCP
    port: 80     # Le port auquel le service sera exposé
    targetPort: 8080  # Le port sur lequel votre application est en cours d'exécution
  type: LoadBalancer
