version: 2

sources:
  - name: source
    database: source
    schema: weather
    tables:
      - name: weather

  - name: sourcesilver
    database: lakehouse
    schema: silver
    tables:
      - name: weathersil
